PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gpdb_src
- name: sqldump

outputs:
- name: artifacts
- name: sqldump

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    # assume greenplum is fresh and has only system databases

    ccp_src/scripts/setup_ssh_to_cluster.sh
    ssh -t mdw 'mkdir -p /home/gpadmin/sqldump'
    scp sqldump/* mdw:/home/gpadmin/sqldump/
    ssh -t mdw 'xz -d /home/gpadmin/sqldump/dump.sql.xz'

    # (1) Generate & run script to load data to DB, backup the DB, and export the backup artifact
    cat <<SCRIPT > /tmp/generate_backup_artifact.bash
      set -ex
      source env.sh

      mkdir /tmp/backup_artifact # parent dir for all backups

      echo "##### Loading sqldump into DB #####"
      psql -d postgres -f /home/gpadmin/sqldump/dump.sql

      echo "##### Running pg_dump on regression DB #####"
      pg_dump regression -f /tmp/regression_dump.sql
      xz -z /tmp/regression_dump.sql

      # iterate through all the databases (skipping system ones)
      psql -t postgres -c "SELECT datname FROM pg_database WHERE datistemplate = false;" > /tmp/db_names
      # must use index rather than db name, to support special char db: "funny copy""db'with\\quotes"
      db_index=-1
      while read -r db ; do
        [ -z "\${db}" ] && continue
        db_index=\$((db_index+1))
        dir="/tmp/backup_artifact/\${db_index}"
        mkdir "\${dir}"

        echo "##### Backing up database: \${db} #####"
        gpbackup --dbname "\${db}" --backup-dir "\${dir}" #--verbose
      done < /tmp/db_names

      # create tarball of all backups by backing up parent dir
      pushd /tmp ; tar -czvf backup_artifact.tar.gz backup_artifact ; popd
    SCRIPT

    chmod +x /tmp/generate_backup_artifact.bash
    scp /tmp/generate_backup_artifact.bash mdw:/home/gpadmin/generate_backup_artifact.bash
    ssh -t mdw "bash  /home/gpadmin/generate_backup_artifact.bash"

    ssh -t sdw1 "pushd /tmp ; tar -czvf backup_artifact.tar.gz backup_artifact ; popd"

    mkdir /tmp/gpbackup_allsegments
    scp mdw:/tmp/regression_dump.sql.xz  sqldump/
    scp mdw:/tmp/backup_artifact.tar.gz  /tmp/gpbackup_allsegments/gpbackup_mdw.tar.gz
    scp sdw1:/tmp/backup_artifact.tar.gz /tmp/gpbackup_allsegments/gpbackup_sdw1.tar.gz

    pushd /tmp; tar czvf gpbackup_all.tar.gz gpbackup_allsegments ; popd
    mv /tmp/gpbackup_all.tar.gz artifacts/

